name: CI Development

defaults:
  run:
    working-directory: Digital-Technologies-Radar-task

on:
  pull_request:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: '14'

      - name: install
        run: |
          yarn install

      - name: build
        env:
          REACT_APP_GOOGLE_MAPS_API_KEY: ${{ secrets.GOOGLE_MAPS_API_KEY }}
        run: |
          yarn build

      - name: test
        run: |
          yarn test
        env:
          NODE_ENV: development
          CI: true
